apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: test2
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
