{{- $AppName :=  .Values.appname -}}
{{- $AppNameSpaces :=  .Values.appnamespaces -}}

--- 	

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-{{ $AppName }}
subjects:
  - kind: ServiceAccount
    name: {{ $AppName }}
    namespace: {{ $AppNameSpaces }}
roleRef:
  kind: Role
  name: leader-locking-{{ $AppName }}
  apiGroup: rbac.authorization.k8s.io
  
---
