kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-client-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "create", "update", "patch", "list", "watch"]
